#!/usr/bin/env bash
# =============================================================================
# create-secrets.sh — create all out-of-band (git-ignored) secrets a freshly
# provisioned cluster needs. Idempotent: safe to re-run.
#
# Run AFTER `terraform apply` (platform-base has created the kind cluster +
# Argo CD) and BEFORE `kubectl apply -f bootstrap/root-app.yaml` — the Argo repo
# credentials must exist before the app-of-apps tries to sync the private repos.
#
# Covers:
#   1. Argo CD repository credentials  (namespace: argocd)
#   2. platform-tls wildcard cert      (namespaces: openbao harbor keycloak
#                                        engineering-platform)
#   3. GHCR pull credentials           (namespace: harbor)
#   4. Harbor pull robot + secret      (namespace: engineering-platform)
#      — NOT in `all`: needs Harbor's API LIVE, so run it LATER (after root-app
#        has synced and Harbor is Healthy):  ./create-secrets.sh harbor-pull
#
# Secret VALUES live in git-ignored files (repo-credentials*.yaml,
# harbor-replication/ghcr-credentials.yaml) and in a generated platform-tls
# cert/key. This script contains NO secrets itself.
#
# Usage:
#   ./create-secrets.sh [all|repo-creds|tls|ghcr]      (default: all)
#   ./create-secrets.sh harbor-pull                    (run after Harbor Healthy)
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
ok()   { printf '  \033[1;32m✓\033[0m %s\n' "$*"; }
skip() { printf '  \033[1;33m•\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# Namespaces that host an Ingress referencing secretName: platform-tls, PLUS
# cert-manager (the cluster-resource-namespace where the platform-tls-ca
# ClusterIssuer resolves its CA — see apps/security/cert-manager and the SPIRE
# OIDC provider's tls.certManager, which signs that provider's serving cert from
# this stable CA so OpenBao's pinned oidc_discovery_ca_pem never goes stale).
PLATFORM_TLS_NS="openbao harbor keycloak engineering-platform cert-manager"

# Cert/key location: generated by Terraform (platform-base/platform-tls.tf),
# written here (git-ignored); this script only distributes them. Override with
# PLATFORM_TLS_CERT / PLATFORM_TLS_KEY to use a cert you keep elsewhere.
TLS_CRT="${PLATFORM_TLS_CERT:-$SCRIPT_DIR/platform-tls.crt}"
TLS_KEY="${PLATFORM_TLS_KEY:-$SCRIPT_DIR/platform-tls.key}"

require_cluster() {
  command -v kubectl >/dev/null || die "kubectl not found in PATH"
  kubectl cluster-info >/dev/null 2>&1 || die "kubectl cannot reach a cluster (check your context)"
  log "Target context: $(kubectl config current-context)"
}

ensure_ns() {  # ensure_ns <namespace> — created bare if missing; Argo adopts it later.
  kubectl get ns "$1" >/dev/null 2>&1 || kubectl create ns "$1" >/dev/null
}

# ---- 1. Argo CD repository credentials --------------------------------------
apply_repo_creds() {
  log "Argo CD repository credentials (namespace: argocd)"
  ensure_ns argocd

  # Required: without this, root-app cannot authenticate to the private GitOps repo.
  if [ -f "$SCRIPT_DIR/repo-credentials.yaml" ]; then
    kubectl apply -f "$SCRIPT_DIR/repo-credentials.yaml" >/dev/null
    ok "platform-infra repo creds"
  else
    die "$SCRIPT_DIR/repo-credentials.yaml missing (git-ignored).
       Copy repo-credentials-example.yaml -> repo-credentials.yaml and fill in your GitHub PAT."
  fi

  # Optional: demo application repos.
  for f in repo-credentials-demo-go.yaml repo-credentials-demo-py.yaml; do
    if [ -f "$SCRIPT_DIR/$f" ]; then
      kubectl apply -f "$SCRIPT_DIR/$f" >/dev/null; ok "$f"
    else
      skip "$f not present — its demo repos won't sync (optional)"
    fi
  done
}

# ---- 2. platform-tls wildcard cert ------------------------------------------
# The cert/key are GENERATED by Terraform (platform-base/platform-tls.tf) and
# written to bootstrap/platform-tls.{crt,key}; this step only DISTRIBUTES that
# one cert into each namespace with an Ingress that references it. Generating it
# in Terraform (not here) is what lets Argo CD's OIDC rootCA use it on the first
# apply, breaking the keycloak-secret chicken-and-egg — see that file's comment.
apply_platform_tls() {
  log "platform-tls wildcard cert for *.127.0.0.1.sslip.io"

  if [ ! -f "$TLS_CRT" ] || [ ! -f "$TLS_KEY" ]; then
    die "platform-tls cert/key not found:
         $TLS_CRT
         $TLS_KEY
       These are generated by Terraform (platform-base). Run 'terraform apply' first,
       or set PLATFORM_TLS_CERT / PLATFORM_TLS_KEY to a cert you keep elsewhere."
  fi
  ok "using cert at $TLS_CRT"

  for ns in $PLATFORM_TLS_NS; do
    ensure_ns "$ns"
    kubectl -n "$ns" create secret tls platform-tls \
      --cert="$TLS_CRT" --key="$TLS_KEY" \
      --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    ok "platform-tls in $ns"
  done

  # Harbor's chart (caBundleSecretName: harbor-ca-bundle) wants the SAME cert
  # under key `ca.crt`, so harbor-core trusts platform-tls when reaching
  # Keycloak's OIDC discovery. Without it harbor-core hangs on a missing-secret
  # mount. Generic (not tls) secret, ca.crt key.
  ensure_ns harbor
  kubectl -n harbor create secret generic harbor-ca-bundle \
    --from-file=ca.crt="$TLS_CRT" \
    --dry-run=client -o yaml | kubectl apply -f - >/dev/null
  ok "harbor-ca-bundle in harbor"
}

# ---- 3. GHCR pull credentials for harbor-replication ------------------------
apply_ghcr() {
  log "GHCR pull credentials (namespace: harbor)"
  local f="$INFRA_DIR/apps/integration-delivery/harbor-replication/ghcr-credentials.yaml"
  if [ -f "$f" ]; then
    ensure_ns harbor
    kubectl apply -f "$f" >/dev/null; ok "ghcr-replication-credentials"
  else
    skip "ghcr-credentials.yaml not present — Harbor GHCR replication won't authenticate.
       Copy ghcr-credentials.example.yaml -> ghcr-credentials.yaml and fill in a read:packages PAT."
  fi
}

# ---- 4. Harbor pull robot + imagePullSecret ---------------------------------
# UNLIKE the steps above, this needs Harbor's API to be LIVE — Harbor is deployed
# by Argo CD (root-app), i.e. only AFTER this script's `all` run. So it is NOT in
# `all`; run it separately once Harbor is Synced & Healthy.
#
# Harbor's `platform` project is private, so the teams-* Deployments in
# engineering-platform pull with the `harbor-pull` imagePullSecret — backed by a
# project-scoped, pull-only Harbor robot. (Tenant namespaces get their own pull
# secret from teams-operator; only the platform's own namespace must be
# bootstrapped here, since the operator can't create its own pull secret before
# it can pull its own image.) Both the robot (Harbor DB) and the k8s secret are
# wiped on a cluster rebuild, so this recreates them idempotently. Replaces the
# manual "step 3" robot creation in README.md.
HARBOR_URL="${HARBOR_URL:-https://harbor.127.0.0.1.sslip.io:8443}"
HARBOR_ADMIN_PASSWORD="${HARBOR_ADMIN_PASSWORD:-Harbor12345}"
HARBOR_PULL_NS="${HARBOR_PULL_NS:-engineering-platform}"

apply_harbor_pull() {
  log "Harbor pull robot + imagePullSecret (namespace: $HARBOR_PULL_NS)"
  command -v jq >/dev/null || die "jq not found in PATH (needed to parse Harbor's robot response)"
  ensure_ns "$HARBOR_PULL_NS"

  local api="$HARBOR_URL/api/v2.0" auth="admin:$HARBOR_ADMIN_PASSWORD"

  # Wait for Harbor's API — it may still be syncing when this is run.
  local i=0
  until [ "$(curl -sk -o /dev/null -w '%{http_code}' -u "$auth" "$api/systeminfo" || true)" = "200" ]; do
    i=$((i + 1))
    [ "$i" -gt 30 ] && die "Harbor API not reachable at $api after 30 tries — is Harbor Synced & Healthy?"
    skip "waiting for Harbor API ($i/30)…"; sleep 5
  done
  ok "Harbor API reachable"

  # Resolve the platform project id — Harbor won't list project-scoped robots
  # without an explicit ProjectID in the query (the plain /robots list, which
  # only shows SYSTEM robots, silently omits them).
  #
  # On a fresh cluster the `platform` project doesn't exist until the GHCR
  # replication first pushes into it (Harbor auto-creates it then), which lags
  # Harbor becoming Healthy. So wait for it rather than failing outright — this
  # lets `make bootstrap` run this step end-to-end without a manual pause.
  local pid="" j=0
  while [ -z "$pid" ]; do
    pid=$(curl -sk -u "$auth" "$api/projects?name=platform" | jq -r '.[0].project_id // empty')
    [ -n "$pid" ] && break
    j=$((j + 1))
    [ "$j" -gt 60 ] && die "Harbor 'platform' project not found after 5m — has GHCR replication run yet? (check the harbor-replication job)"
    skip "waiting for Harbor 'platform' project ($j/60)…"; sleep 5
  done

  # A project-scoped robot's secret is returned ONLY at creation and can't be
  # read back, so to stay idempotent we delete any existing `pull` robot, then
  # recreate it and capture the fresh secret. Full name is robot$platform+pull;
  # project robots must be queried with q=Level=project,ProjectID=<id>.
  local existing_id
  existing_id=$(curl -sk -u "$auth" -G "$api/robots" \
    --data-urlencode "q=Level=project,ProjectID=$pid" --data "page_size=100" 2>/dev/null \
    | jq -r '.[] | select(.name=="robot$platform+pull") | .id' | head -1 || true)
  if [ -n "$existing_id" ]; then
    curl -sk -u "$auth" -X DELETE "$api/robots/$existing_id" >/dev/null || true
    skip "deleted stale robot id=$existing_id (its secret can't be re-read)"
  fi

  local resp rname rsecret
  resp=$(curl -sk -u "$auth" -X POST "$api/robots" -H 'Content-Type: application/json' -d '{
    "name":"pull","duration":-1,"level":"project",
    "permissions":[{"kind":"project","namespace":"platform",
      "access":[{"resource":"repository","action":"pull"}]}]}')
  rname=$(echo "$resp" | jq -r '.name // empty')
  rsecret=$(echo "$resp" | jq -r '.secret // empty')
  [ -n "$rname" ] && [ -n "$rsecret" ] \
    || die "robot creation failed: $(echo "$resp" | jq -c '{errors}' 2>/dev/null || echo "$resp")"
  ok "robot $rname created"

  kubectl -n "$HARBOR_PULL_NS" create secret docker-registry harbor-pull \
    --docker-server=harbor.127.0.0.1.sslip.io \
    --docker-username="$rname" \
    --docker-password="$rsecret" \
    --dry-run=client -o yaml | kubectl apply -f - >/dev/null
  ok "harbor-pull imagePullSecret in $HARBOR_PULL_NS"
}

main() {
  require_cluster
  case "${1:-all}" in
    all)         apply_repo_creds; apply_platform_tls; apply_ghcr ;;
    repo-creds)  apply_repo_creds ;;
    tls)         apply_platform_tls ;;
    ghcr)        apply_ghcr ;;
    harbor-pull) apply_harbor_pull ;;
    *)           die "unknown target '$1' (use: all | repo-creds | tls | ghcr | harbor-pull)" ;;
  esac
  log "Done."
}

main "$@"
