apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDropCapabilities
metadata:
  name: tenant-drop-capabilities
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaceSelector:
      matchExpressions:
        - key: teams.example.com/team-id
          operator: Exists
  parameters:
    allowedCapabilities: []
