apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequireContainerResources
metadata:
  name: tenant-require-container-resources
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaceSelector:
      matchExpressions:
        - key: teams.example.com/team-id
          operator: Exists
