apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequireDigestProduction
metadata:
  name: tenant-require-digest-production
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaceSelector:
      matchExpressions:
        - key: environment
          operator: In
          values: ["production"]
