apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequireGovernanceLabels
metadata:
  name: tenant-require-governance-labels
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
    namespaceSelector:
      matchExpressions:
        - key: teams.example.com/team-id
          operator: Exists
  parameters:
    requiredLabels: ["team", "owner", "cost-center", "environment"]
